theme: jekyll-theme-cayman
title: "Welcome to My Homepage!"
name: ""
baseurl: ""
description: >
    <style>
        main {
            margin-left: 330px !important;
            max-width: 800px !important;
        }

        header {
            margin-left: 330px !important;
        }

        .sidebar {
            position: fixed;
            top: 0;
            left: 0;
            width: 280px;
            height: 100vh;
            background-color: #ffffff;
            border-right: 1px solid #ddd;
            padding: 40px 20px;
            box-shadow: 2px 0 6px rgba(0, 0, 0, 0.1);
            text-align: center;
            z-index: 1000;
        }

        .sidebar img {
            width: 160px;
            height: 200px;
            border-radius: 60%;
            object-fit: cover;
            margin-bottom: 15px;
        }

        .sidebar h1 {
            font-size: 22px;
            color: #003366;
            margin-bottom: 8px;
        }

        .sidebar p {
            font-size: 15px;
            color: #555;
            margin: 5px 0;
        }

        .sidebar a {
            color: #007acc;
            text-decoration: none;
            font-size: 15px;
        }

        .sidebar a:hover {
            text-decoration: underline;
        }
    </style>

    <div class="sidebar">
        <img src="images/Yassine.jpg" alt="Profile Picture">
        <h1>Yassine Nabou</h1>
        <p>Postdoctoral researcher</p>
        <p style="font-size: 15px;">
            Department of Mathematics and Statistics <br>
            University of Helsinki, Finland <br>
            Exactum building, office B326
    </p>
    <p style="font-size: 14px;">
        ‚Ä¢ üìß <a href="mailto:yassine.nabou@helsinki.fi">Email</a> <br>
        ‚Ä¢ üéì <a href="https://scholar.google.com/citations?user=YourScholarID" target="_blank">Google Scholar</a> <br>
        ‚Ä¢ üßë‚Äçüî¨ <a href="https://www.linkedin.com/in/yassine-nabou-aba88114b/" target="_blank">LinkedIn</a> <br>
        ‚Ä¢ üîó <a href="https://orcid.org/0009-0004-9805-8039" target="_blank">ORCID</a>
    </p>
    </div>
